
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"

install:
  - "pip install nose"
  - "pip install coveralls"
  - "pip install --upgrade pip"
  - "pip install -e .[testing]"

script:
  - "nosetests -v"

after_success:
  - coveralls
